//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADONBAN
    {
        public int MaChiTiet { get; set; }
        public Nullable<int> MaHoaDonBan { get; set; }
        public Nullable<int> MaSP { get; set; }
        public int SoLuongBan { get; set; }
        public int DonGiaBan { get; set; }
        public int GiamGia { get; set; }
        public Nullable<int> ThanhTienBan { get; set; }
    
        public virtual HOADONBAN HOADONBAN { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
