//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONBAN()
        {
            this.CT_HOADONBAN = new HashSet<CT_HOADONBAN>();
        }
    
        public int MaHoaDonBan { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> TongTienBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADONBAN> CT_HOADONBAN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
