//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CSDL_QuanLyCuaHangBanNuocHoa : DbContext
    {
        public CSDL_QuanLyCuaHangBanNuocHoa()
            : base("name=CSDL_QuanLyCuaHangBanNuocHoa")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_HOADONBAN> CT_HOADONBAN { get; set; }
        public virtual DbSet<HOADONBAN> HOADONBANs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAI> LOAIs { get; set; }
        public virtual DbSet<NHANHIEU> NHANHIEUx { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
    
        public virtual ObjectResult<getHoadon_Result> getHoadon(Nullable<int> makhachhang)
        {
            var makhachhangParameter = makhachhang.HasValue ?
                new ObjectParameter("makhachhang", makhachhang) :
                new ObjectParameter("makhachhang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHoadon_Result>("getHoadon", makhachhangParameter);
        }
    
        public virtual ObjectResult<getCTHoadon_Result> getCTHoadon(Nullable<int> mahoadon)
        {
            var mahoadonParameter = mahoadon.HasValue ?
                new ObjectParameter("mahoadon", mahoadon) :
                new ObjectParameter("mahoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCTHoadon_Result>("getCTHoadon", mahoadonParameter);
        }
    
        public virtual ObjectResult<getHoadonAdmin_Result> getHoadonAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHoadonAdmin_Result>("getHoadonAdmin");
        }
    
        public virtual int removehoadon(Nullable<int> mahoadon)
        {
            var mahoadonParameter = mahoadon.HasValue ?
                new ObjectParameter("mahoadon", mahoadon) :
                new ObjectParameter("mahoadon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removehoadon", mahoadonParameter);
        }
    
        public virtual int removetaikhoan(Nullable<int> makh)
        {
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removetaikhoan", makhParameter);
        }
    
        public virtual int updatetaikhoan(Nullable<int> makh, string ten, string diaChi, string dienThoai, Nullable<System.DateTime> ngaySinh, string tenTaiKhoan, string matKhau)
        {
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var tenTaiKhoanParameter = tenTaiKhoan != null ?
                new ObjectParameter("TenTaiKhoan", tenTaiKhoan) :
                new ObjectParameter("TenTaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatetaikhoan", makhParameter, tenParameter, diaChiParameter, dienThoaiParameter, ngaySinhParameter, tenTaiKhoanParameter, matKhauParameter);
        }
    
        public virtual int deletetaikhoan(Nullable<int> makh)
        {
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletetaikhoan", makhParameter);
        }
    
        public virtual int xoakhachhang(Nullable<int> makh)
        {
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoakhachhang", makhParameter);
        }
    }
}
