//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CT_HOADONBAN = new HashSet<CT_HOADONBAN>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string NongDo { get; set; }
        public string NhomHuong { get; set; }
        public string MoTaSanPham { get; set; }
        public Nullable<int> NamPhatHanhSanPham { get; set; }
        public string AnhSanPham { get; set; }
        public Nullable<int> MaNhanHieu { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> DungTich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADONBAN> CT_HOADONBAN { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual NHANHIEU NHANHIEU { get; set; }
    }
}
